# Generated by Django 6.0.2 on 2026-02-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
