# Generated by Django 6.0.2 on 2026-02-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_student_enrollment_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
