# Generated by Django 6.0.1 on 2026-01-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_subject_subjectmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmarks',
            name='marks',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=50),
        ),
    ]
